server:
  port: 7001
  error:
    include-message: always

logging:
  level:
    root: INFO
    io.anjola: DEBUG

---
spring:
  config:
    activate:
      on-profile:
        - docker

server:
  port: 8080
